name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: docker/build-push-action@v6
        with:
          tags: anarkiwi/nuviemaker:latest
